version: '3.8'

services:
  email-engine-core:
    build: ./api
    image:  email-engine-core
    container_name: email-engine-core
    ports:
      - '3000:3000'
      - '3019:3019'
    depends_on:
      - elasticsearch
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules

  email-engine-core-ui:
    build: ./frontend
    image:  email-engine-core-ui
    container_name: email-engine-core-ui
    ports:
      - '3001:3000'
    depends_on:
      - email-engine-core
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic1234578
    ports:
      - '9200:9200'
      - '9300:9300'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elastic:elastic1234578@elasticsearch:9200
    depends_on:
      - elasticsearch
